# netlify.toml

node_version = "22.16.0"

[build]
  command = "npm run generate-meta && npm run build && npx next export"
  publish = "out"

[[plugins]]
package = "@netlify/plugin-nextjs"

  [plugins.inputs]
  skip = true
