export const HOME_OG_IMAGE_URL = ''
export const SITE_TITLE = 'JennTesolin.com'
export const SEARCH_URL = '/search/'
export const SITE_URL = 'https://nextjs-jenn-tes-f8e9r.ondigitalocean.app/'
export const SITE_AUTHOR = 'Jennifer Tesolin'
export const ARTICLE_LICENSE = 'http://creativecommons.org/licenses/by-nc-sa/3.0/'
export const SITE_DOMAIN = 'https://nextjs-jenn-tes-f8e9r.ondigitalocean.app//'
export const COPYRIGHT = `&copy; ${new Date().getFullYear()} Jennifer Tesolin.`
export const SITE_DESCRIPTION = `${SITE_TITLE}'s website for beginners.`
export const BLOG_TITLE = 'Blog'