export const HOME_OG_IMAGE_URL = ''
export const SITE_TITLE = 'JennTesolin.com'
export const SEARCH_URL = '/search/'
export const SITE_URL = 'https://jenntesolin.com/'
export const SITE_AUTHOR = 'Jennifer Tesolin'
export const ARTICLE_LICENSE_LINK = 'https://creativecommons.org/licenses/by-nc-sa/4.0/'
export const ARTICLE_LICENSE_TEXT = 'CC BY-NC-SA 4.0'
export const SITE_DOMAIN = 'https://jenntesolin.com/'
export const COPYRIGHT = `&copy; ${new Date().getFullYear()} Jennifer Tesolin.`
export const SITE_DESCRIPTION = `${SITE_TITLE}'s website for beginners.`
export const BLOG_TITLE = 'Blog'