export const HOME_OG_IMAGE_URL = ''
export const SITE_TITLE = 'JennTesolin.com'
export const SEARCH_URL = '/search/'
export const SITE_AUTHOR = 'Jennifer Tesolin'
export const ARTICLE_LICENSE = 'http://creativecommons.org/licenses/by-nc-sa/3.0/'